image:
  - "Visual Studio 2017"

shallow_clone: false

environment:
  MINGW_DIR: C:\msys64\mingw64\bin
  Path: C:\Python34-x64\;%MINGW_DIR%;%Path%
  matrix:
    -
      BUILD_TYPE: release
      CMAKE_BUILD: cygwin
      STATIC_LIBS: true
      UNIT_TESTS: true
      CYGWIN_NOWINPATH: yes
      clone_folder: "C:\\cygwin\\projects\\NJOY2016"
      CYG_BASH: C:\cygwin\bin\bash
      CYG_CACHE: C:\cygwin\var\cache\setup
      CYG_MIRROR: http://cygwin.mirror.constant.com
      CYG_ROOT: C:\cygwin
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      FC: /usr/bin/gfortran
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MSYS
      STATIC_LIBS: true
      UNIT_TESTS: true
      clone_folder: "C:\\projects\\NJOY2016"
      CC: "%MINGW_DIR%\\gcc.exe"
      CXX: "%MINGW_DIR%\\g++.exe"
      FC: "%MINGW_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MSYS
      STATIC_LIBS: false
      UNIT_TESTS: true
      clone_folder: "C:\\projects\\NJOY2016"
      CC: "%MINGW_DIR%\\gcc.exe"
      CXX: "%MINGW_DIR%\\g++.exe"
      FC: "%MINGW_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MinGW
      STATIC_LIBS: true
      UNIT_TESTS: true
      clone_folder: "C:\\projects\\NJOY2016"
      CC: "%MINGW_DIR%\\gcc.exe"
      CXX: "%MINGW_DIR%\\g++.exe"
      FC: "%MINGW_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MinGW
      STATIC_LIBS: false
      UNIT_TESTS: true
      clone_folder: "C:\\projects\\NJOY2016"
      CC: "%MINGW_DIR%\\gcc.exe"
      CXX: "%MINGW_DIR%\\g++.exe"
      FC: "%MINGW_DIR%\\gfortran.exe"
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\Program Files\\Git\\usr\\bin"
      #
      #clone_folder: 
      #  - if [%CMAKE_BUILD%]==[cygwin] "C:\\cygwin\\projects\\NJOY2016"
      #  - if not [%CMAKE_BUILD%]==[cygwin] "C:\\projects\\NJOY2016"

init:
  - if [%CMAKE_BUILD%]==[cygwin] git config --global core.autocrlf input

install:
  - if [%CMAKE_BUILD%]==[cygwin] C:\cygwin\setup-x86.exe -q --root %CYG_ROOT% --local-package-dir %CYG_CACHE% --packages cmake,make,git,python3,gcc-core,gcc-g++,gcc-fortran --force-current --no-shortcuts --no-startmenu --no-desktop

before_build:
  - if [%CMAKE_BUILD%]==[cygwin] dir C:\cygwin\
  - if not [%CMAKE_BUILD%]==[cygwin] set OrigPath=%Path%
  - if [%CMAKE_BUILD%]==[cygwin] set Path=C:\cygwin\bin
    #  - if [%CMAKE_BUILD%]==[cygwin] set Path=%Path:C:\Program Files\Git\usr\bin;=%

build_script:
  - mkdir build
  - cd build
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "/usr/bin/cmake -D build_type=%BUILD_TYPE% -D static=%STATIC_LIBS% -D unit_tests=%UNIT_TESTS% -G \"Unix Makefiles\" .."
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "/usr/bin/make -j2"
# Non-cygwin builds
  - if not [%CMAKE_BUILD%]==[cygwin] set Path=%TMP_PATH%
  - if not [%CMAKE_BUILD%]==[cygwin] cmake -D CMAKE_Fortran_COMPILER=C:/msys64/mingw64/bin/gfortran.exe -D CMAKE_MAKE_PROGRAM=C:/msys64/mingw64/bin/mingw32-make.exe -D static=%STATIC_LIBS% -D unit_tests=%UNIT_TESTS% -G "%CMAKE_BUILD% Makefiles" ..
  - if not [%CMAKE_BUILD%]==[cygwin] set Path=%OrigPath%
  - if not [%CMAKE_BUILD%]==[cygwin] mingw32-make -j2

after_build:
  - if [%CMAKE_BUILD%]==[cygwin] %CYG_BASH% -c "cd tests/03 && ../../njoy.exe <input"
  - if not [%CMAKE_BUILD%]==[cygwin] ctest -j2 --output-on-failure
